### PR TITLE
Conda build3 update

### PR DESCRIPTION
**Pull request by blowekamp**
This PR is a combination of #20 and #21

### CODE REVIEW

**Comment by blowekamp** [comment]
@ihnorton  This patch incorporates your change, thank you for the fix!

**Comment by blowekamp** [comment]
It is unclear to me why appveyor.yml was removed by the robot in 24e77d3a50749bacb41fe9a944b3673e18a78cfd

**Comment by ihnorton** [comment]
Great, thanks. I've been working on a few more changes to build with ITK5. Current ITK master builds fine, but was waiting to submit PR until beta2/3 comes out. (also having issues building ANTS against this lib due to HDF5 issue mentioned in #7)

**Comment by blowekamp** [comment]
With the appveyor missing I may try to[ rereneder with conda-smithy](https://conda-forge.org/docs/conda_smithy.html) to update the build infrastructure.

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@blowekamp everything seems to be up-to-date.

**Comment by bgruening** [comment]
@conda-forge-admin, please update for conda-build 3

**Comment by bgruening** [comment]
@blowekamp you can use the [webservices](https://conda-forge.org/docs/webservice.html) to trigger re-rendering or upgrading the recipes.

**Comment by blowekamp** [comment]
That is some very cool automatic services!

The CI error is related to VS9 (2008):

```
312  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 125, in get_env_dependencies
313    channel_urls=tuple(m.config.channel_urls))
314  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 750, in get_install_actions
315    raise DependencyNeedsBuildingError(exc, subdir=subdir)
316conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'vc==14', 'vc=9'}
317
```

This package is suppose to be a "system" like library package which does not depend on Python. Are Python 2.7/VC9 builds still being done/supported?

**Comment by blowekamp** [comment]
@ihnorton  @bgruening Looks like we have this build working again in the time constraints! This looks read to merge...

**Comment by bgruening** [comment]
Cool thanks!

**Pull request merged**
