### PR TITLE
Rename itk to libitk in README

### PR DESCRIPTION
**Pull request by thewtex**
This documentation update follows the package rename.

For #10

### CODE REVIEW

**Comment by thewtex** [comment]
@jjhelmus @msarahan Do you have the admin privileges or do you know who does to enable `conda-forge/libitk-feedstock` in AppVeyor?

**Comment by blowekamp** [comment]
@jjhelmus @msarahan Can we get some help with enabling AppVeyor for this repo after it was renamed?

Thanks!

**Comment by msarahan** [comment]
Returning from vacation. I can take a look later tonight.

**Comment by msarahan** [comment]
Sorry guys, looks like I don't have adequate permissions to change anything about the conda-forge stuff on appveyor.  @ocefpaf @jakirkham may be better equipped.

**Comment by ocefpaf** [comment]
> Sorry guys, looks like I don't have adequate permissions to change anything about the conda-forge stuff on appveyor.

We need to fix that :smile: 

But here it is: https://ci.appveyor.com/project/conda-forge/libitk-feedstock

**Comment by thewtex** [comment]
Super, thanks @ocefpaf @msarahan !

**Pull request merged**
