### PR TITLE
Aarch cross

### PR DESCRIPTION
**Pull request by hmaarrfk**
Just want to see if cross compiling aarch works
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blowekamp** [comment]
As I recall there were CMake "try_run"s or code generation tools used for configurations which prevented cross compilation working out of the box.

**Comment by hmaarrfk** [comment]
>  "try_run"s or code generation tools

At conda-forge, the `try_run` will fail on osx-arm since it has cross compilation, but no emulation.

For aarch and ppc64le, emulation is made available so it should be fine. Mostly this is a quality of life improvement, not waiting forever for the builds to finish is nice....

**Comment by hmaarrfk** [comment]
well i'm going to  close this, but its good for you to know that at least it seems to work....

**Comment by blowekamp** [comment]
Thank you for this. I am trying it with libsimpleitk as it was timing out with the native build.

**Comment by blowekamp** [comment]
More specifically, the following passes precomputed try compile results:
https://github.com/conda-forge/libitk-feedstock/blob/1374e15747412aee18c34db2273abc89a9262c70/recipe/build.sh#L20

A file similar to this should be needed for aarch 64:
https://github.com/conda-forge/libitk-feedstock/blob/main/recipe/TryRunResults-osx-arm64.cmake

CMake documentation for generating this can be found here:
https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#using-compile-checks

**Pull request closed without merging**
